### ISSUE TITLE
Setting the color.a of a TypingLabel actor makes the FADE token not work properly.

### ISSUE THREAD

**Issue by UnbackedFan** [rafaskb/typing-label#26]
I have a use case in my app where I need to apply a scene2d fade Action to a TypingLabel while it's currently applying the FADE token. However, when changing the alpha channel of the TypingLabel's color, the FADE effect is ignored.

The code below works as expected. The fading occurs normally.
```
TypingLabel test = new TypingLabel("", Utils.getDefaultLabelStyle(MY_GAME.smallFont));
test.getColor().a = 1f;
test.restart("{SLOWER}{FADE=0;1;2.5} THIS IS A TEST THIS IS A TEST{ENDFADE}");
```

However, in this code, the fading effect is ignored. 
```
TypingLabel test = new TypingLabel("", Utils.getDefaultLabelStyle(MY_GAME.smallFont));
test.getColor().a = 0.8f;
test.restart("{SLOWER}{FADE=0;1;2.5} THIS IS A TEST THIS IS A TEST{ENDFADE}");
```

**Comment by tommyettinger** [comment]
It looks like the latest commit built just recently, probably when you requested the SNAPSHOT build of my branch. In case it isn't working, https://jitpack.io/#tommyettinger/typing-label/run-color-fix-SNAPSHOT should have the current dependency. I really like how JitPack updates commits so readily, but their SNAPSHOT builds sometimes need Gradle to be told to refresh dependencies, if an older version is still considered the most current on your machine.

**Comment by rafaskb** [comment]
@tommyettinger am I correct to assume this issue is fixed with your latest changes in PR https://github.com/rafaskb/typing-label/pull/25? Running the test on my end with the `issue26.txt` and enabling `label.getColor().a = 0.5f` produce the result you showed in the video above, which I believe is the expected outcome right?
If so I can close this, as I'm about to merge the PR and push a new release 😁
